### ISSUE TITLE
Error when starting a feature

### ISSUE THREAD

**Issue by IDisposable** [joshfischer1108/GBRestructure#14]
Starting a feature in a clean repo (maybe something not fetched yet?) gives this error

```
09:40 $ gb foxstart AddEditorConfig
Traceback (most recent call last):
  File "/usr/local/bin/gb", line 9, in <module>
    load_entry_point('GBRestructure==0.4.0', 'console_scripts', 'gb')()
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/restructure/gb.py", line 103, in cli
    startOperation(branch_type_or_cmd, action, provided_name, tag_message, FOXHOUND)
  File "/Library/Python/2.7/site-packages/restructure/gb.py", line 120, in startOperation
    printer.showError("branch type doesn't exist: " + branch_type)
NameError: global name 'printer' is not defined
```

**Comment by joshfischer1108** [comment]
Resolved.  Will be out in next release.

**Comment by joshfischer1108** [comment]
version 0.4.2 has been pushed to pip.
